In [1]:
from random import randint
import numpy as np
import matplotlib.pyplot as plt

In [13]:
class TrainDataLoader:
    def __init__(self):
        pass
    
    def GenerateRandomData(self,count,gradient,offset):
        x1 = np.linspace(1,5,count)
        x2 = gradient*x1 + np.random.randint(-10,10,*x1.shape) + offset
        dataset = []
        y = []
        for i in range(*x1.shape):
            dataset.append([x1[i],x2[i]])
            real_value = gradient * x1[i] + offset
            if real_value > x2[i]:
                y.append(-1)
            else:
                y.append(1)
        return x1,x2,np.mat(y),np.mat(dataset)

In [14]:
train_data = TrainDataLoader()
x,y,result,train_data = train_data.GenerateRandomData(10,2,10)

In [15]:
x

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [16]:
y

array([ 2.        ,  6.88888889, 13.77777778, 21.66666667,  7.55555556,
        6.44444444, 21.33333333, 12.22222222, 14.11111111, 18.        ])

In [17]:
result

matrix([[-1, -1,  1,  1, -1, -1,  1, -1, -1, -1]])

In [18]:
train_data

matrix([[ 1.        ,  2.        ],
        [ 1.44444444,  6.88888889],
        [ 1.88888889, 13.77777778],
        [ 2.33333333, 21.66666667],
        [ 2.77777778,  7.55555556],
        [ 3.22222222,  6.44444444],
        [ 3.66666667, 21.33333333],
        [ 4.11111111, 12.22222222],
        [ 4.55555556, 14.11111111],
        [ 5.        , 18.        ]])

In [24]:
a = np.array([1,2,3])
b = np.array([1,2,3])
np.dot(a,b.T)

14

In [ ]:
class Perceptron_hand:
    def __init__(self,train_data=[],real_result=[],eta=1):
        self.w = np.zeros([1,len(train_data.T)],int)
        self.b = 0
        slef.eta = eta
        self.train_data = train_data
        self.real_result = real_result
    def normalize(self,x):
        if x > 0:
            return 1;
        else:
            return -1
    def model(self,x):
        y = np.dot(x,self.w.T) +self.b
        predict_v = self.normalize(y)
        return predict_v,y
    def update(self,x,y):
        self.w = self.w + self.eta*y*x
        self.b = self.b + self.eta*y