In [2]:
from random import randint
import numpy as np
import matplotlib.pyplot as plt

In [3]:
class TrainDataLoader:
    def __init__(self):
        pass
    
    def GenerateRandomData(self,count,gradient,offset):
        x1 = np.linspace(1,5,count)
        x2 = gradient*x1 + np.random.randint(-10,10,*x1.shape) + offset
        dataset = []
        y = []
        for i in range(*x1.shape):
            dataset.append([x1[i],x2[i]])
            real_value = gradient * x1[i] + offset
            if real_value > x2[i]:
                y.append(-1)
            else:
                y.append(1)
        return x1,x2,np.mat(y),np.mat(dataset)

In [4]:
train_data = TrainDataLoader()
x,y,result,train_data = train_data.GenerateRandomData(10,2,10)

In [5]:
x

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [6]:
y

array([20.        , 11.88888889,  5.77777778, 10.66666667, 14.55555556,
       19.44444444,  8.33333333, 16.22222222, 10.11111111, 19.        ])

In [7]:
result

matrix([[ 1, -1, -1, -1, -1,  1, -1, -1, -1, -1]])

In [8]:
train_data

matrix([[ 1.        , 20.        ],
        [ 1.44444444, 11.88888889],
        [ 1.88888889,  5.77777778],
        [ 2.33333333, 10.66666667],
        [ 2.77777778, 14.55555556],
        [ 3.22222222, 19.44444444],
        [ 3.66666667,  8.33333333],
        [ 4.11111111, 16.22222222],
        [ 4.55555556, 10.11111111],
        [ 5.        , 19.        ]])

In [10]:
fx = np.array([1.2,2.3,3.3])
fx.astype(int)

array([1, 2, 3])

In [15]:
class Perceptron_hand:
    def __init__(self,train_data=[],real_result=[],eta=1):
        self.w = np.zeros([1,len(train_data.T)],int)
        self.b = 0
        self.eta = eta
        self.train_data = train_data
        self.real_result = real_result
    def normalize(self,x):
        if x > 0:
            return 1;
        else:
            return -1
    def model(self,x):
        y = np.dot(x,self.w.T) +self.b
        predict_v = self.normalize(y)
        return predict_v,y
    def update(self,x,y):
        self.w = self.w + self.eta*y*x
        self.b = self.b + self.eta*y
    def loss(self,fx,y):
        return fx.astype(int)*y
    def train(self,count):
        update_count = 0
        while count > 0:
            count = count - 1
            if len(self.train_data) <= 0:
                print("exception exit")
                break
            index = randint(0,len(self.train_data)-1)
            x = self.train_data[index]
            y = self.real_result[index]
            predict_v,linear_y_v = self.model(x)
            if self.loss(y,linear_y_v) > 0:
                continue
            update_count = update_count + 1
            self.update(x,y)
        print("update count:",update_count)
        pass
    def verify(self, verify_data, verify_result):
        size = len(verify_data)
        failed_count = 0
        if size <= 0:
            pass
        for i in range(size):
            x = verify_data[i]
            y = verify_result.T[i]
            if self.loss(y, self.model(x)[1]) > 0:
                continue
            failed_count = failed_count + 1
        success_rate = (1.0 - (float(failed_count)/size))*100
        print("Success Rate: ", success_rate, "%")
        print("All input: ", size, " failed_count: ", failed_count)
    def predict(self, predict_data):
        size = len(predict_data)
        result = []
        if size <= 0:
            pass
        for i in range(size):
            x = verify_data[i]
            y = verify_result.T[i]
            result.append(self.model(x)[0])
        return result

        
            

In [17]:
# gradient = 2
# offset   = 10
# point_num = 1000
# train_num = 50000
# loader = TrainDataLoader()
# x, y, result, train_data =  loader.GenerateRandomData(point_num, gradient, offset)
# x_t, y_t, test_real_result, test_data =  loader.GenerateRandomData(100, gradient, offset)

# # First training
# perceptron = Perceptron_hand(train_data, result)
# perceptron.train(train_num)
# perceptron.verify(test_data, test_real_result)
# print("T1: w:", perceptron.w," b:", perceptron.b)

# # Draw the figure
# # 1. draw the (x,y) points
# plt.plot(x, y, "*", color='gray')
# plt.plot(x_t, y_t, "+")
# # 2. draw y=gradient*x+offset line
# plt.plot(x,x.dot(gradient)+offset, color="red")
# # 3. draw the line w_1*x_1 + w_2*x_2 + b = 0
# plt.plot(x, -(x.dot(float(perceptron.w.T[0]))+float(perceptron.b))/float(perceptron.w.T[1])
#          , color='green')
# plt.show()


IndexError: index 780 is out of bounds for axis 0 with size 1